### ISSUE TITLE
Disable TaskDialog "hyperlink" functionality

### ISSUE THREAD

**Issue by RussKie** [kpreisser/winforms#4]
During an internal usability study for the `TaskDialog` API, all participant had troubles showing a hyperlink. Eventually few users were able to find how set it up. Then users were confused that they had to implement a handler. 

> _This is weird that I can specify a link, but TaskDialog would not go there for me, I have to implement the handler. I'd prefer it to be implemented for me._

I propose we disable the hyperlink functionality for the time-being until the `TaskDialog` functionality is merged into Windows Forms codebase.
Whilst the hyperlink functionality is certainly very appealing, it is not a core functionality of `TaskDialog`, and we won't be significantly degrading the UX by not making it available to our user in the first iteration. 
Making it less confusing for users would require additional efforts that are best directed to other issues.

**Comment by kpreisser** [comment]
I removed the hyperlink functionality.
