### ISSUE TITLE
[minor] `MainInstruction` is confusing

### ISSUE THREAD

**Issue by RussKie** [kpreisser/winforms#6]
During an internal usability study for the TaskDialog API, all users found `MainInstruction` name unclear and confusing. 
> \- _To me instruction is a paragraph, not the heading. Maybe I'll call it `Header`_
\- _MainInstruction was not clear. I'd rather call it Heading_

We had an internal discussion and resolved that we shouldn’t necessarily align our naming to underlying Win32 API if it causes confusion for Windows Forms users.

**Comment by kpreisser** [comment]
I think I would rename it to `Heading`. 
(I think `Header` would be similar to `Footer` and would imply that it's a separate area like the footer, but actually it's only a text line.)

**Comment by kpreisser** [comment]
I renamed the property to `Heading`.

**Comment by RussKie** [comment]
Awesome. thank you
