### ISSUE TITLE
Limit number of buttons

### ISSUE THREAD

**Issue by RussKie** [kpreisser/winforms#7]
I couldn't quite see (perhaps I am just missing it) whether `TaskDialog` imposes any limit on number of buttons, both at the bottom of the dialog and commandlink style.

`MessageBox` limits number of buttons to three. Typically anything more than that would overwhelm a user, e.g. Notepad++ has (or had) a dialog with 5(!) buttons:
![image](https://user-images.githubusercontent.com/4403806/73914773-088c3e80-490e-11ea-9465-08800ef7cdef.png)

I suggest limiting number of buttons at the bottom and commandlinks of the dialog to no more then five (each).
If more buttons added than the limit, throw an exception.

**Comment by kpreisser** [comment]
The native task dialog API (and current .NET API) don't limit the number of buttons that can be shown in the dialog.
However, do you think it's really necessary to impose such a limit (when the native API doesn't)?

For example, in developer scenarios, users might want to show a dialog with all of the existing standard buttons to check how it would look like (e.g. button order).

Another scenario is that we (at work) applied the task dialog as a simple way to have the user select an entry from a list which should be used, so we dynamically generate the command link buttons. (It's probably not the best way to get such input from the user, but as a short-term solution it works).
However, while the list normally only contains few entries (3-5), in some cases it may contain more than that, and in that case we wouldn't be able to show a task dialog any more.

**Comment by RussKie** [comment]
My proposal stems from the fact that too much choice presents a cognitive overload and confuses majority of users.
I've re-read https://docs.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box and it doesn't any specific guidance on a number of buttons. Though none of the examples had more than 3 buttons.

@merriemcgaw @OliaG do we have any contacts in Windows UX team who could give us some guidance here?

**Comment by merriemcgaw** [comment]
I personally don't I'm afraid. But I will dig around to see if someone knows someone 😀

**Comment by merriemcgaw** [comment]
The following might be dated but should answer a few questions around layout and buttons: 
- [Design basics for Desktop applications](https://docs.microsoft.com/en-us/windows/win32/uxguide/designprinciples)
- [Messages](https://docs.microsoft.com/en-us/windows/win32/uxguide/messages)
- [Dialog Boxes](https://docs.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box)

@oliag can you get the VS Design UX people and ask around for Windows content?

**Comment by RussKie** [comment]
Found few examples on the web, and I personally think all of them are madness:

![image](https://user-images.githubusercontent.com/4403806/74787425-43757580-5303-11ea-8c3d-d1facbf8a2da.png)
![image](https://user-images.githubusercontent.com/4403806/74787428-496b5680-5303-11ea-9501-9e08392e1a87.png)
![image](https://user-images.githubusercontent.com/4403806/74790113-c817c200-530a-11ea-928e-dbe09dc7d9b1.png)

**Comment by merriemcgaw** [comment]
Yeah, those are all a bit much. I'm thinking 3-4 is a good limit.

**Comment by RussKie** [comment]
I had a chat with @terrajobst and he convinced me (not that I was hard set on this anyway) that limiting consumers in this case would likely result in more headache for us.
So I'm closing this.
