### ISSUE TITLE
Consider renaming `Footer` to `Footnote`

### ISSUE THREAD

**Issue by RussKie** [kpreisser/winforms#8]
During an internal usability study for the TaskDialog API, some users were confused by `Footer`

> _If there is a Footer, why there's no Header?_
> _Footer without header??_

https://docs.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box uses "Footnote" name. Perhaps it is worth renaming the control to use that name.

**Comment by kpreisser** [comment]
I renamed it to `Footnote`/`TaskDialogFootnote`.

**Comment by RussKie** [comment]
Awesome, thank you
